export default [
  {
    id:'01',
    title:'商品管理',
    children:[
      {
        id:'0101',
        title:'商品管理',
        children:[
          {
            id:'010101',
            title:'新增',
          },
          {
            id:'010102',
            title:'修改',
          },
          {
            id:'010103',
            title:'删除',
          },
          {
            id:'010104',
            title:'导入',
          },
          {
            id:'010105',
            title:'导出',
          }

        ]
      },{
        id:'0102',
        title:'类型管理',
        children:[
          {
            id:'010201',
            title:'新增',
          },
          {
            id:'010202',
            title:'修改',
          },
          {
            id:'010203',
            title:'删除',
          }

        ]
      },
      {
        id:'0103',
        title:'订单管理',
      }
    ]
  },
  {
    id:'02',
    title:'券类管理',
    children:[
      {
        id:'0201',
        title:'立减券管理',
        children:[
          {
            id:'020101',
            title:'新增',
          },
          {
            id:'020102',
            title:'修改',
          },
          {
            id:'020103',
            title:'删除',
          }

        ]
      },
      {
        id:'0202',
        title:'积分卡管理',
        children:[
          {
            id:'020201',
            title:'新增',
          },
          {
            id:'020202',
            title:'修改',
          },
          {
            id:'020203',
            title:'删除',
          }

        ]
      }

    ]
  },
  {
    id:'03',
    title:'权限管理',
    children:[
      {
        id:'0301',
        title:'账号管理',
        children:[
          {
            id:'030101',
            title:'新增',
          },
          {
            id:'030102',
            title:'修改',
          },
          {
            id:'030103',
            title:'删除',
          }

        ]
      },
      {
        id:'0302',
        title:'角色管理',
        children:[
          {
            id:'030201',
            title:'新增',
          },
          {
            id:'030202',
            title:'修改',
          },
          {
            id:'030203',
            title:'删除',
          }

        ]
      }
    ]
  }
]
